### ISSUE TITLE
`smaug build` recursively copies all builds into the current game

### ISSUE THREAD

**Issue by travishaynes** [ereborstudios/smaug#50]
To reproduce: Create two separate games in separate paths and build each one, then look in each game's build directory. They'll have the builds for all the games, not just the one you're working on.

It looks like Smaug is recursively copying all of the files from the build directory of the DragonRuby installation. Smaug should take care to only copy the build files that were generated only for the current game.

**Comment by bedwardly-down** [comment]
I second this issue. It happens on my Gentoo instance but I have 4 different “game” projects that it does it with.

@travishaynes what operating system are you having this issue on, what version of dragonruby, and where are you storing your game directories? 

OS: Gentoo
DR: all 3.0 releases so far
Directory Structure: $HOME/git/<Project Directory>

My DR is installed under $HOME/.cache/smaug/dragonruby-pro-amd64

**Comment by travishaynes** [comment]
@bedwardly-down I'm running Ubuntu 21.10, DragonRuby 3.0 Pro. Games are in `~/projects/`, DragonRuby was installed by Smaug to `~/.local/share/smaug/dragonruby/`.
