### ISSUE TITLE
Installation instructions on webpage are wrong?

### ISSUE THREAD

**Issue by dkam** [ereborstudios/smaug#51]
Hi there - thanks for making Smaug!

The [install](https://smaug.dev/install/) instructions say: 

`smaug install ~/Downloads/dragonruby-linux-amd64.zip`

![image](https://user-images.githubusercontent.com/18232/138374145-da80569c-3ee5-4863-b534-122b2d4c0042.png)

This results in: 

```bash
➜  ~ smaug install DragonRuby/dragonruby-gtk-macos.zip
error: Found argument 'DragonRuby/dragonruby-gtk-macos.zip' which wasn't expected, or isn't valid in this context

If you tried to supply `DragonRuby/dragonruby-gtk-macos.zip` as a PATTERN use `-- DragonRuby/dragonruby-gtk-macos.zip`

USAGE:
    smaug install [FLAGS] [OPTIONS]

For more information try --help
```

The git repo says it should be:

`smaug dragonruby install ~/Downloads/dragonruby-linux-amd64.zip.zip`

Which worked for me ( with the Mac-gtk version )

**Comment by guitsaru** [comment]
Thanks. This has been fixed.
