### ISSUE TITLE
Cannot install DragonRuby >= 3.0

### ISSUE THREAD

**Issue by kfischer-okarin** [ereborstudios/smaug#52]
DragonRuby from version 3.0 starts using a `CHANGELOG-CURR.txt` instead of `CHANGELOG.txt` so the install command cannot properly determine the version of the zip file.

So it would be good to also look for both `CHANGELOG-CURR.txt` or `CHANGELOG.txt`

**Comment by travishaynes** [comment]
Yeah, this is a breaking issue. I had to manually rename the change log file inside the zip before I could install it using Smaug.

**Comment by marcheiligers** [comment]
#53 fixes this. I'm no rustacean though, so happy to make changes as needed.
