### ISSUE TITLE
Cannot add dragonruby zip

### ISSUE THREAD

**Issue by dangerdyke** [ereborstudios/smaug#54]
`smaug dragonruby install /path/to/dragonruby.zip` fails with the following error:
```
thread 'main' panicked at 'Couldn't find DragonRuby: DragonRubyNotFound { path: "/home/[user]/.cache/smaug/dragonruby-linux-amd64" }', cli/src/commands/dragonruby/install.rs:36:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
smaug version: 0.3.2
dragonruby version: 3.2
os: linux/endeavourOS
shell: fish v3.1.1

steps to reproduce:
1. install smaug through the AUR package, as directed by the install instructions
2. attempt to install a dragonruby zip

**Comment by marcheiligers** [comment]
See #52 and my related PR for a fix.
