### ISSUE TITLE
Smaug Run Failing on Windows 11

### ISSUE THREAD

**Issue by bshea5** [ereborstudios/smaug#65]
Getting a blank screen when running `smaug run`? I've run smaug install on my drgk zip and can see it in my list. But running smaug run in my new project, I just get a blank screen.
Windows 11
smaug 0.5.1
dragonruby pro 3.20
![image](https://user-images.githubusercontent.com/3984775/189567086-9b09ee7c-8f4a-41e3-8639-7a329c77bccd.png)

game meta data:
```
# This file was automatically @generated by Smaug.
# Do not manually edit this file. Edit Smaug.toml instead.

devid=todo-change-me
devtitle=My Name &lt;todo@example.com&gt;
gameid=first
gametitle=first
version=0.1.0
icon=metadata/icon.png
compile_ruby=false
```

To me, the Game Dir defined looks odd:
![image](https://user-images.githubusercontent.com/3984775/189567161-1c8424a9-5970-4a59-a4d9-30ca00faed6c.png)

**Comment by Eric-Guo** [comment]
Me too, but it works at DragonRuby 3.15, so possible relative with 3.16~3.18 changes.

**Comment by bshea5** [comment]
Submitted a PR, https://github.com/ereborstudios/smaug/pull/66

**Comment by guitsaru** [comment]
Thanks @bshea5. Your change is out in v0.5.2 and up on scoop
